name: Update Nogizaka Calendar

on:
  schedule:
    # 毎日 日本時間の深夜2時（サーバーの標準時で17時）に自動実行
    - cron: '0 17 * * *'
  workflow_dispatch: # ボタンを押して手動で動かせる機能もオンにする

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 基地にファイルを書き込む権限をロボットに与える

    steps:
      - name: 基地のデータを読み込む
        uses: actions/checkout@v4

      - name: Pythonの準備
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 必要な道具（requests）のインストール
        run: pip install requests

      - name: 乃木坂カレンダープログラムを実行！
        run: python main.py

      - name: 作成されたカレンダー（.ics）を基地に保存する
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add oshi_schedule.ics
          # 変更があった場合のみ保存（コミット）する
          git diff --quiet && git diff --staged --quiet || (git commit -m "カレンダーを自動更新しました" && git push)
