name: Update Nogizaka Calendar

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 基地のデータを読み込む
        uses: actions/checkout@v4

      - name: Pythonの準備
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 必要な道具（requests）のインストール
        run: pip install requests

      - name: 乃木坂カレンダープログラムを実行！
        run: python main.py

      - name: 作成されたカレンダー（.ics）を基地に保存する
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add oshi_schedule.ics
          # もし変更があれば、最新状態を取り込んでから保存（push）する！
          if ! git diff --quiet --staged; then
            git commit -m "カレンダーを自動更新しました"
            git pull --rebase origin main
            git push origin main
          fi
